package bfrc.java.jit;

import java.io.IOException;

/**
 * Interface for all classes generated by the JIT compiler.
 * 
 * @author oreissig
 */
public interface JITBlock {

	public int call(final JITContext c) throws IOException;
}
